api:
  base_url: https://api.crocdb.net
  max_retries: 3
  retry_delay: 1
  timeout: 30
cache:
  enabled: true
  max_size_mb: 100
  ttl_hours: 24
directories:
  logs: logs
  roms: ROMs
  temp: temp
download:
  chunk_size: 8192
  download_boxart: true
  max_concurrent: 4
  preferred_hosts: []
  timeout: 300
  verify_downloads: true
interface:
  confirm_downloads: true
  language: en_us # auto, en_us, pt_br, es_es, ru_ru, etc.
  show_progress: true
  theme: default
logging:
  console_enabled: false
  file_enabled: true
  level: INFO
  max_log_files: 10
  max_log_size_mb: 10
performance:
  mirror_test_file_size: 1048576
  mirror_test_timeout: 10
  test_mirrors: true
search:
  max_results: 100
  results_per_page: 10
